### ISSUE TITLE
Aggiungere Call To Action all'inizio delle liste degli issue

### ISSUE THREAD

**Issue by luciroma** [emergenzeHack/ukrainehelp.emergenzehack.info#108]
**Priorità**: alta

## Testo della comunicazione

Inserire questa frase all'inizio delle liste degli issue "Hai un'iniziativa o una richiesta da inviare?" Segnala qui. E mettere link a form.
@mfortini non riesco ad assegnartela direttamente che non ho i poteri, ma ti taggo.
A me piace la tua idea e anzi grazie!

**Comment by cristigalas** [comment]
Io proporrei più semplicemente e sinteticamente:
_Hai una segnalazione? Inviala!_

Così andrebbe bene per tutto.

**Comment by luciroma** [comment]
Non sono certa che "segnalazione" sia comprensibile per tutti rispetto a cosa segnalare, io lascerei una frase che dice subito già alcune delle cose che si possono segnalare, già chiarificatrice insomma, poi una volta dentro al form ovviamente ci sono anche tutte le altre categorie.

**Comment by Patriziacar** [comment]
A me piace "Hai un'iniziativa o una richiesta da inviare?"

**Comment by cristigalas** [comment]
Ok @mfortini allora procediamo con _Hai un'iniziativa o una richiesta da inviare?" Segnala qui._
