### ISSUE TITLE
Categorizzazione iniziative nazionali

### ISSUE THREAD

**Issue by Patriziacar** [emergenzeHack/ukrainehelp.emergenzehack.info#112]
Molte iniziative che stiamo raccogliendo riguardano spesso molti territori e regioni diverse.
Nella pagina "segnalazioni per regione" possiamo introdurre anche la categoria "Nazionali" per raccogliere le iniziative che sono attive su diverse regioni?
C'è un modo anche per segnalare sulla mappa le iniziative nazionali?

**Priorità**: bassa

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by cristigalas** [comment]
@Patriziacar si potrebbe aggiungere a mano **Regioni: Tutte**, come si faceva su Covid19Italia.help. Lo aveva ideato @mfortini così comparivano in tutte le regioni. Matteo possiamo attivarlo anche qui?

**Comment by luciroma** [comment]
Ciao, questa issue è risolta? @cristigalas @iltempe

**Comment by cristigalas** [comment]
@luciroma no, @mfortini non ha mai risposto :(

**Comment by mfortini** [comment]
@cristigalas @luciroma ho verificato: Regioni: "tutte" (tutto minuscolo) funziona e fa vedere la issue in tutte le regioni.

Non saprei come georiferire una segnalazione nazionale...

**Comment by cristigalas** [comment]
Molto bene @mfortini. 
Allora @luciroma @Patriziacar faremo cosi, mi pare la via più semplice. Piano piano quindi cerchiamo di inserire _Regioni: “tutte”_ nelle principali segnalazioni di interesse nazionale.

**Comment by cristigalas** [comment]
@mfortini ho provato ma non funziona. Ho inserito Regione: “tutte” a questa segnalazione e non compare in tutte le regioni https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/682

Comunque segnalo che sul sito tutta la sezione Regioni /Provincie non funziona bene. La gran parte delle segnalazioni non compare nelle varie regioni e provincie di riferimento nonostante la presenza delle coordinate 😞

**Comment by mfortini** [comment]
Per quanto riguarda la questione "tutte le regioni", ho recuperato il sistema di gestione e ho sistemato ad esempio segnalazione 682, vedi per riferimento https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/682

Si deve inserire la stringa:
`regione_manuale: tutte`

**Comment by mfortini** [comment]
> @mfortini ho provato ma non funziona. Ho inserito Regione: “tutte” a questa segnalazione e non compare in tutte le regioni [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#682](https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/682)
> 
> Comunque segnalo che sul sito **[tutta la sezione Regioni/Provincie](https://ukrainehelp.emergenzehack.info/issues/regione/) non funziona bene**. La gran parte delle segnalazioni non compare nelle varie regioni e provincie di riferimento nonostante la presenza delle coordinate disappointed

@cristigalas per quanto riguarda questo, riesci a darmi un numero di segnalazione da verificare? Grazie

**Comment by cristigalas** [comment]
> Per quanto riguarda la questione "tutte le regioni", ho recuperato il sistema di gestione e ho sistemato ad esempio segnalazione 682, vedi per riferimento [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#682](https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/682)
> 
> Si deve inserire la stringa: `regione_manuale: tutte`

Ok mi pare funzioni adesso. Però dovresti togliere dalla scheda della segnalazione sul sito il campo _regione manuale: tutte_. È brutto e susuperfluo. Grazie!
