### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/ukrainehelp.emergenzehack.info#13]
Any ideas?

**Priorità**: bassa

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by cristigalas** [comment]
@iltempe @mfortini Come logo sul sito (in alto a sinistra) possiamo mettere semplicemente i colori della bandiera ucraina così come è sui social? Quello che c’è adesso non capisco bene cosa sia, ma visto che nel dominio adesso c’è Ukraine i colori della bandiera ci stanno bene, secondo me.

E poi nella barra di navigazione compare il loghino di Covid19Italia. Andrebbe tolto.

**Comment by luciroma** [comment]
Sì esatto, concordo con Cristina. Attualmente confermo che nella barra di navigazione compare ancora il loto Covid19

**Comment by luciroma** [comment]
@iltempe il logo è ok, mentre nella barra di navigazione si vede ancora covid19

**Comment by iltempe** [comment]
@favoeva mitica! chiudo
