### ISSUE TITLE
Creazione della sezione "Normativa di riferimento" 

### ISSUE THREAD

**Issue by luciroma** [emergenzeHack/ukrainehelp.emergenzehack.info#134]
**Priorità**: bassa

## Richiesta

Poiché si sono susseguite e si susseguiranno diverse normative per garantire protezione e accoglienza alle persone in fuga dalla guerra in Ucraina, potrebbe essere utile avere una sezione dove le raccogliamo tutte? Ora credo siano in news e di certo sono recuperabili per parole chiave ma avere tutte in una pagina potrebbe essere un servizio apprezzato.

Che ne dite? Nel caso, servirà chiedere agli sviluppatori di crearla e di fare un pò si trasferimento segnalazioni.

@cristigalas @favoeva @iltempe 

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by mfortini** [comment]
Proposta 1: usare il formato "post" e aggiungerle in quella sezione. Si inseriscono scrivendo "l'articolo" e facendo una PR

**Comment by cristigalas** [comment]
@luciroma ma è davvero necessario farla? Io sono perplessa… Se penso all’esperienza di Tci e Covid19 il problema è poi tenerla aggiornata per non sentirsi dire da qualcuno “ah ma questa non c’è!”. Altro problema è quello di organizzarla al suo interno per evitare che diventi un elenco informe e inconsultabile. Al tempo di Covid19 ci ragionammo parecchio a riguardo e la cosa era complessa...

Del resto esistono già enti, anche istituzionali, che sui loro siti raccolgono la normativa sull’emergenza Ucraina (che è già parecchia e al solito frammentata tra più enti), a partire dal portale Integrazione Migranti del governo https://integrazionemigranti.gov.it/it-it/Dettaglio-approfondimento/id/44/Emergenza-Ucraina#norme
Oppure Cinformi https://www.cinformi.it/Progetti/Speciale-Emergenza-Ucraina/Emergenza-Ucraina-normativa-e-ordinanze

Comunque se proprio vogliamo farla credo che la cosa più semplice sia attivare una nuova label NORMATIVA e aggiungerla ad ogni issue con normativa. Poi trasformare la label in pagina-categoria sul sito. 
Al momento la normativa è in _Documenti_*. Continuerei ad usare quella come form e poi aggiungerei label Normativa alla segnalazione, semmai togliendo label Documenti (mi pare una ridondanza inutile). 
Non appena abbiamo aggiunto la nuova label a tutte le issue già presenti che riguardano la normativa, possiamo attivare la nuova pagina-categoria. 

*_Ad oggi mi pare che abbiamo solo tre issue con normative: [qui](https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/398), [qui](https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/278) e [qui](https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/133), più una ordinanza regionale ([Campania](https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/394))._

**Comment by luciroma** [comment]
_"Al momento la normativa è in Documenti*. Continuerei ad usare quella come form e poi aggiungerei label Normativa alla segnalazione, semmai togliendo label Documenti (mi pare una ridondanza inutile)"_

Per me va bene procedere così intanto: contrassegnamo quelle segnalazioni che sono specificatamente normative, poi vediamo se attivare la pagina correlata in un secondo momento. Concordo con te che, se ne abbiamo poche, non ha senso avere una pagine dedicata.

**Comment by cristigalas** [comment]
@luciroma ho attivato label Normativa e l'ho inserita alle 4 issue che segnalano normative. Ricordiamoci di usarla @favoeva @patriziacar

Chiudo.
