### ISSUE TITLE
Segnalazioni georiferite, ma non appaiono in Regione e Provincia

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/ukrainehelp.emergenzehack.info#136]
@mfortini ad es. questa non c'è ma sono molte https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/718

_Originally posted by @cristigalas in https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info/issues/112#issuecomment-1110039347_

**Comment by mfortini** [comment]
Fixed in github2CSV.py

**Comment by cristigalas** [comment]
@mfortini scusa Matteo hai chiuso ma devi ancora sistemare giusto? Perché la sezione regioni continua a non avere tutte le issue che dovrebbe...

**Comment by mfortini** [comment]
> @mfortini scusa Matteo hai chiuso ma devi ancora sistemare giusto? Perché la sezione regioni continua a non avere tutte le issue che dovrebbe...

Ho verificato la segnalazione https://ukrainehelp.emergenzehack.info/issues/718/ e la vedo sia in Regione Piemonte, che in Provincia di Novara @cristigalas c'è qualche altro esempio?

**Comment by cristigalas** [comment]
@mfortini Sì sì Ora funziona. Grazie!
