### ISSUE TITLE
Sito da mettere online in Ucraino - habemus traduzione

### ISSUE THREAD

**Issue by luciroma** [emergenzeHack/ukrainehelp.emergenzehack.info#138]
**Priorità**: bassa

## Richiesta

Ciao, abbiamo fatto tradurre le pagine della piattaforma in ucraino. Ora serve metterlo online.
La traduzione la trovate qui: 
https://docs.google.com/document/d/1JonxP3xB6UkF7utFh9KH6daY39KE-avX/edit?usp=sharing&ouid=104858539274543061381&rtpof=true&sd=true 

@mfortini @iltempe @avivace 

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by girolamodaschio** [comment]
Lavorando da browser, ho fatto confusione con #143 e #144. 
Ad ogni modo adesso sono pronti contribute, about e sto per inserire anche contatti.

**Comment by girolamodaschio** [comment]
Dovremmo essere messi così:
se così fosse, @luciroma puoi copiare questa lista sul primo commento

- [x] Contatti
- [x] About
- [x] Contribute
- [x] Index
- [x] Issues
- [ ] Legal segnalazioni
- [ ] Notizie
- [ ] Opendata
- [ ] Partners
- [ ] Policy
- [ ] Regioni
- [ ] Segnala
- [ ] Segnala_embed
- [ ] wiki
- [ ] Faq

**Comment by girolamodaschio** [comment]
Contatti mi sembra ci sia, ho aggiornato anche la checklist di segnala dopo aver visto pull di @abonte

**Comment by luciroma** [comment]
La pagina contatti e anche la checklist di segnala mi danno anche il messaggio "404 not found", non so come mai?
Potete provare a vedere? 
Grazie

**Comment by abonte** [comment]
problemi risolti in #148 e #142
Grazie

**Comment by abonte** [comment]
_report_ dovrebbe essere risolto, _contact_ è risolto qui #142, ma la richiesta di modifica non è ancora stata accettata
cc @mfortini @iltempe

**Comment by luciroma** [comment]
stiamo facendo tradurre l'informativa per la privacy e le due form "richieste di aiuto" e "segnala iniziative e servizi", non appena pronte le carico qui, così aggiungiamo anche queste e il sito in UA per noi è ok, poi faremo una piccola uscita media per dirlo. Grazie molte a tutti voi
