### ISSUE TITLE
Update Ukrainian translation

### ISSUE THREAD

**Issue by abonte** [emergenzeHack/ukrainehelp.emergenzehack.info#151]
**Priorità**: alto

## Richiesta

Traduzioni in ucraino come indicato in chat Telegram

- [x] ПОВІДОМИТИ (segnalare)
- [x] ЗНАЙТИ (cercare/scoprire)
- [x] ПРО ПРОЕКТ (cos'è questo progetto )
- [x] ПРИЙНЯТИ УЧАСТЬ (partecipare)  ДОПОМОГТИ (aiutare)
UkraineHelp avrei lasciato senza la traduzione 
- [x] Збір та розповсюдження корисної інформації та послуг на підтримку в надзвичайній ситуації в Україні (ho cercato a fare la traduzione più vicina alla descrizione originale)
- [x] ПОВІДОМИТИ (segnalare)
- [x] ЗАПИТИ ПРО ДОПОМОГУ (richieste di aiuto) 
- [x] ІНІЦІАТИВИ (iniziative) 
- [x] УСІ ПОВІДОМЛЕННЯ (tutte le segnalazioni)
- [x] РЕГІОН (regione)

## Risolto?

* [x] Ho verificato che il problema è stato risolto

**Comment by luciroma** [comment]
@girolamodaschio @mfortini @iltempe
