### ISSUE TITLE
Cover Facebook Group

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/ukrainehelp.emergenzehack.info#18]
To create a cover for our facebook group 
https://www.facebook.com/groups/449673436901610/?notif_id=1646083400458299&notif_t=groups_member_joined&ref=notif

**Priorità**: bassa

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by cristigalas** [comment]
Intanto ho messo come copertina Fb la card che avevi creato tu @iltempe

**Comment by favoeva** [comment]
pensate che questi potrebbero aiutare ?

https://www.facebook.com/122148481172635/posts/4806332192754217/?d=n

**Comment by cristigalas** [comment]
@favoeva perché no? Potremmo intanto chiedere... semmai anche per il logo (vedi #13) e poi card per promuovere il progetto sui social (mi sono allargata ;)

**Comment by favoeva** [comment]
<img width="470" alt="3BAC77E1-48C1-428C-839D-D02BC6E9B1AF" src="https://user-images.githubusercontent.com/9965333/158080060-4c1ac729-7aa1-4fbd-bb9c-e8fc2292bfc6.png">

**Comment by favoeva** [comment]
Ho cambiato il font e modificato qualcosa nella call to action 
Ne farei anche una in italiano

**Comment by favoeva** [comment]
Aiutaci a raccogliere e diffondere dati aperti sugli aiuti a sostegno dei civili ucraini

**Comment by cristigalas** [comment]
@favoeva nella card da qualche parte metterei il nome del progetto Ukraine Help sennò facciamo confusione. Ad esempio, nel testo centrale della card (che farei senz'altro anche in italiano) metterei qualcosa tipo:
_Partecipa al progetto Ukraine Help 
per raccogliere e diffondere info utili a supporto del popolo ucraino_

**Comment by favoeva** [comment]
Ok mi torna tutto 👍stasera faccio nuova card

**Comment by cristigalas** [comment]
@iltempe no, card e cover non ci sono ancora. Anche @Albertopi78 si è offerto di lavorarci, vediamo se arrivano chiudi.

**Comment by iltempe** [comment]
questa si può chiudere?

**Comment by cristigalas** [comment]
Secondo me sì
