### ISSUE TITLE
Coordination and Channels

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/ukrainehelp.emergenzehack.info#3]
telegram opened to everybody to share informations https://t.me/ukraineinfohelp
slack JUST to develop and organization https://join.slack.com/t/ukrainfohelp/shared_invite/zt-14af4khvq-BgvGVa4Wkahst4NsUBZy4A
Other channels?

**Comment by favoeva** [comment]
Aperto gruppo Facebook https://www.facebook.com/groups/449673436901610/?ref=share

**Comment by iltempe** [comment]
@favoeva let the name ukraineinfo.help ... #6 is the name of the website..facebook group can be several with different names. thanks!!!!!!

**Comment by favoeva** [comment]
> opened a Facebook group https://www.facebook.com/groups/449673436901610/?ref=share
> 
> let me know if it has to be renamed after the url of the project #6

group renamed here’s the new url 
https://www.facebook.com/groups/ukraineinfo.help

**Comment by cristigalas** [comment]
Mattermost https://mm.emergenzehack.info/signup_user_complete/?id=tqkbawqgptfnbxp4mk7oow5t4r
