### ISSUE TITLE
Pagina Privacy sul sito

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/ukrainehelp.emergenzehack.info#41]
C’è da inserire sul sito la parte su privacy e trattamento dei dati. [Quella di Covid19Italia.help](https://covid19italia.help/legal/) ovviamente non va bene perché c’era ActionAid. Quindi come facciamo, basta riadattare quella? Chi può occuparsene? 

Ps. Nella versione inglese del sito è rimasto il testo della vecchia policy di Covid19Italia. Intanto quella andrebbe tolta.

**Comment by iltempe** [comment]
ne ho parlato con patrizia caruso di AA. sta rivedendo lei con i legali.

**Comment by Patriziacar** [comment]
Ecco la pagina legale in italiano: https://docs.google.com/document/d/1qmZPzWQ3YVkt7JPosJuUpTHHdiK1npuBP4V40Ku_rN4/edit?usp=sharing
E' praticamente identica a quella di covid 19italia.help, sono state fatte piccolissime revisioni, ma andava comunque rivista. Domani arriva la versione inglese

**Comment by Patriziacar** [comment]
Ciao, ecco la versione inglese https://docs.google.com/document/d/1_ssF6wsAbRC0AI3Dn40Zpu8TTySlCxpOlFV7GhFbom4/edit?usp=sharing

**Comment by iltempe** [comment]
chiudo.
