### ISSUE TITLE
Pagine di presentazione del sito riviste e da sostituire

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/ukrainehelp.emergenzehack.info#42]
@iltempe Ho rivisto le pagine del menù in alto. Di seguito i link ai testi che andavano rivisti e che possono essere già inseriti sul sito. Sono in italiano, Patrizia Caruso si occuperà di sistemare la traduzione in inglese.

In giallo ho segnalato le modifiche rispetto a quelli che erano su Covid19Italia.info (ovviamente il giallo va tolto, l’ho messo solo per evidenziare le modifiche). In alcuni casi ho tolto parti intere di testo per semplificare. 

Qui i testi che si possono prendere pari pari e inserire sul sito alle voci corrispondenti (del menù in italiano):

1. **About** https://docs.google.com/document/d/1UIZkzKRzYlOOZ3fSSyffvDj1VtVV8PECMPRDlHKqVCE/edit
2. **Faq** https://docs.google.com/document/d/1g6NeG6RSs_fYgFn2ZVRws96UFMfEeT148kDTITTh__o/edit
3. **Come partecipare**
https://docs.google.com/document/d/1gJ1FXcop0x-uxECOnUNLMbjDJyixXBiGq0CwMly8zMg/edit

**Comment by iltempe** [comment]
ho aggiornato la parte in italiano. appena arrivano quelle in inglese faccio pure quelle.

**Comment by cristigalas** [comment]
> ho aggiornato la parte in italiano. appena arrivano quelle in inglese facciamo le altre.

Scusa Matteo ma i testi che ti ho inviato vanno caricati pari pari, come ti ho scritto sopra, titoli compresi. 
Hai lasciato vecchi titoli e parti di testo che hanno a che fare con la piattaforma Covid. Tipo questa tabella:
![7331AA5B-F03A-44DC-B300-889040C6B390](https://user-images.githubusercontent.com/21283775/158038035-91f64193-20ff-4f9a-8acd-038a1134a92d.jpeg)

Le parti che non vedi nei file che ti ho inviato non ci sono perché le ho tolte. È più semplice se copi e incolli tutto i testi che ti ho inviato, titoli compresi (ripeto ;)

**Comment by iltempe** [comment]
ok grazie. dovrebbe essere a posto adesso.

**Comment by cristigalas** [comment]
A questo punto mancano i testi in inglese e quello sulla privacy che dovrebbero arrivare domani da Patrizia.

**Comment by Patriziacar** [comment]
Ciao, qui i testi in inglese:

About: https://docs.google.com/document/d/1NmV7iF-0WmCcX8l3zno_RZxjdcc7S6rkb_fYprwi0T8/edit
Come contribuire: https://docs.google.com/document/d/1FCHYBdtp4UgtEGLJg9Lpkgi5-ifj_dOjk9OOw4fYAkI/edit
FAQ: https://docs.google.com/document/d/19SCHGRWY-686ZyP86E-crt-isHCOLf3sHYxHOym3VJw/edit

Non sono certamente perfetti quindi se qualcuno vede errori o rifiniture da fare non mi offendo :-)
Vi chiedo anche di controllare i link, mi sono un po' persa con i cambiamenti del fine settimana.
Grazie!

**Comment by iltempe** [comment]
fatto. chiudo.
