### ISSUE TITLE
aggiornare emergenzehack.info

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/ukrainehelp.emergenzehack.info#43]
**Priorità**: bassa

E' da giornare il sito di emergenzehack sul dominio emergenzehack.info dominio già preso.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by avivace** [comment]
Ciao @iltempe . Servono i seguenti record DNS di tipo "A" su emergenzehack.info:

```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

Quando hai fatto, aggiornami pure qui

**Comment by iltempe** [comment]
fatto.

**Comment by avivace** [comment]
> fatto.

Grazie!
