### ISSUE TITLE
Indirizzo posta elettronica del progetto

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/ukrainehelp.emergenzehack.info#44]
Sul sito come indirizzo mail indichiamo europehelp@gmail.com
Forse sarebbe meglio attivare un nuovo indirizzo di posta invece che europehelp visto che non lo usiamo come dominio. Potremmo attivare e usare UkraineHelp@gmail.com oppure emergenzehack@gmail.com se già non esiste. 

Che ne dici @iltempe?

**Comment by iltempe** [comment]
a me va bene. @favoeva ha aperto l'indirizzo mail...non so se si possa modificarlo. se no ne apriamo un altro. lascio a voi. fatemi pure sapere nuovo indirizzo ed aggiorno sito. grazie!!

**Comment by favoeva** [comment]
> a me va bene. @favoeva ha aperto l'indirizzo mail...non so se si possa modificarlo. se no ne apriamo un altro. lascio a voi. fatemi pure sapere nuovo indirizzo ed aggiorno sito. grazie!!

No purtroppo mom si può modificare :(

**Comment by cristigalas** [comment]
E allora ci tocca aprirne un altro.

**Comment by favoeva** [comment]
Creata mail ukrainehelpit@gmail.com 
(Per la gestione Twitter resta europehelp.info@gmail.com)
