### ISSUE TITLE
Testo in home page

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/ukrainehelp.emergenzehack.info#45]
Il testo nella homepage del sito (“Per informare ed informarsi durante la guerra in Ucraina”) secondo me va cambiato. Sembra di un normale sito di informazione e non rende l’idea di ciò che facciamo e chiediamo di fare.

Ragioniamoci… @iltempe @favoeva :)

**Comment by LioKlingo** [comment]
"Favorire l'incontro tra necessità e possibilità in tempo di crisi" o "Favorire l'incontro tra necessità e possibilità al tempo della guerra in Ucraina" o, ancora "Dove le necessità trovano risposte al tempo della guerra in Ucraina"   Qualche spunto per il testo della home

**Comment by cristigalas** [comment]
Forse sarebbe meglio mettere in home ciò che scriviamo sulla card da usare sui social, cosina non usare troppe 'lingue' diverse. 
Quindi potrebbe essere così:

_UkraineHelp
Per raccogliere e diffondere info utili a supporto del popolo ucraino_ o dell'Ucraina

**Comment by LioKlingo** [comment]
Beh sì. Unica variante che suggerisco potrebbe essere:
_Per raccogliere e diffondere info utili a supporto della crisi ucraina_  Visto che ormai anche le nazioni confinanti sono in situazione di crisi per via dell'esodo di persone e di aumentati rischi. Ma forse sto spaccando il capello :)

**Comment by luciroma** [comment]
Le proposta di @LioKlingo mi sembra azzeccata: meglio "crisi ucraina" che non popolo ucraino.
Se aggiungessimo "servizi"?

"Per raccogliere e diffondere info e servizi utili a supporto della crisi Ucraina"?

**Comment by cristigalas** [comment]
@LioKlingo @luciroma sì giusto. E se usiamo la parola emergenza invece di crisi? Cosi da includere i rifugiati e usare una parola a noi familiare e che stanno usando anche tanti enti e associazioni? Quindi tipo:

_Per raccogliere e diffondere info e servizi utili a supporto dell'emergenza Ucraina_

**Comment by luciroma** [comment]
Sì, mi convince!

**Comment by iltempe** [comment]
fatto.
