### ISSUE TITLE
Form "Offer houses" nelle segnalaizoni

### ISSUE THREAD

**Issue by Patriziacar** [emergenzeHack/ukrainehelp.emergenzehack.info#46]
**Priorità**: bassa

## Richiesta
 
Ciao a tutt*. Abbiamo dei dubbi sull'efficacia del form "offer houses". L'offerta di alloggio da parte di singoli è qualcosa che community non possiamo realmente verificare e presenta non pochi rischi. Non mancano tra l'altro iniziative molto strutturate di raccolta disponibilità di alloggi per l'accoglienza. La nostra proposta è quella di eliminare questa opzione e lasciare che le segnalazioni di disponibilità di accoglienza siano insieme alle altre iniziative e servizi.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by cristigalas** [comment]
@Patriziacar concordo. Anch'io stavo pensando la stessa cosa seguendo un po' di gruppi e siti dedicati all'ospitalita. La verificabilità degli alloggi è un lavoro difficile e faticoso, ricordo ai tempi di Tci... E qui tra l'altro la questione è ancora più delicata trattandosi di persone rifugiate, soprattutto donne e bambini. 
Quindi sì, lascerei l'opzione in servizi e poi cercherei di mappare il più possibile siti e servizi dedicati all'ospitalita. Un po' ci sono già ma possiamo ampliare.. 
E poi comunque se qualcun* ha bisogno di alloggio c'è sempre la possibilità di chiedere aiuto e a quel punto ci attiviamo per dare una risposta attraverso i gruppi/servizi già esistenti.

**Comment by iltempe** [comment]
fatto.

**Comment by cristigalas** [comment]
@iltempe un fulmine!! 
Già che ci sei allora nella home in italiano il bottone di iniziative e servizi in realtà è in inglese. Puoi metterlo in italiano? Grazie!
