### ISSUE TITLE
Attivare canale Telegram

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/ukrainehelp.emergenzehack.info#48]
Che ne dite di attivare anche canale Telegram che verrebbe implementato in automatico dal bollettino? (Vedi #47)

Se volete posso occuparmene io.

**Comment by cristigalas** [comment]
Canale Telegram impostato. Quando sarà pubblico inseriamo link e chiudiamo issue.

**Comment by avivace** [comment]
https://t.me/ukrainehelpit
