### ISSUE TITLE
Create Favicon

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/ukrainehelp.emergenzehack.info#49]
Reported by @cristigalas 
Add a simple favicon to replace the old covid19italia one. Maybe a ukraine flag?

**Comment by cristigalas** [comment]
Ok Ukraine flag! Go Antonio go 😜

**Comment by favoeva** [comment]
A me piace anche l’icona del mondo in b/n ma fate voi

**Comment by favoeva** [comment]
Normalmente dovrebbe andarci il logo nel favicon , ma non ce l’abbiamo ancora …

**Comment by cristigalas** [comment]
> A me piace anche l’icona del mondo in b/n ma fate voi

Secondo me sarebbe meglio qualcosa di colorato, ecco perché la bandiera ucraina.

**Comment by cristigalas** [comment]
> > A me piace anche l’icona del mondo in b/n ma fate voi
> 
> Secondo me sarebbe meglio qualcosa di colorato, ecco perché la bandiera ucraina.

Già…

**Comment by iltempe** [comment]
per ora ho aggiornato il logo con la bandiera.

**Comment by mfortini** [comment]
Aggiunte favicon. Riapriamo se arriva icona nuova da @Albertopi78
