### ISSUE TITLE
Twitter meta tags for cards

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/ukrainehelp.emergenzehack.info#50]
Add twitter meta tags on the single report pages to allow rendering Twitter cards with the description of the issue

To preview: https://cards-dev.twitter.com/validator

The tags to set: https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup

**Comment by iltempe** [comment]
@avivace ci stavi lavorando tu?

**Comment by mfortini** [comment]
Dovrebbero essere a posto
