### ISSUE TITLE
titoli nel form rotti

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/ukrainehelp.emergenzehack.info#53]
tutti i titoli dei web form sono nascosti dal menu in alto...qui un esempio.
https://ukrainehelp.emergenzehack.info/forms/segnala_help_page/

**Priorità**: bassa

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by mfortini** [comment]
Fixed in #6cd3d59
