### ISSUE TITLE
Labels per editor

### ISSUE THREAD

**Issue by luciroma** [emergenzeHack/ukrainehelp.emergenzehack.info#57]
**Priorità**: bassa

## Testo della comunicazione

Abbiamo riepilogato in un foglio online quelle etichette che, o se già presenti, sono di nostro particolare interesse perché collegate direttamente ad uno dei filoni di lavoro che, anche attraverso la piattaforma, vorremmo mappare e collegare ai nostri programmi territoriali; si tratta in particolare dei temi: migration/integrazione, decent work (donne), diritti delle donne e accountabilty.
In questo caso, chiediamo la cortesia, da parte di chi edita le segnalazioni, di abbinare sempre altre etichette che ci facciano da "luce spia" per quelle segnalazioni da attenzionare. Abbiamo indicato nelle note del file, alcuni esempio pratici.

Sempre nel file abbiamo segnalato le label che andrebbero invece aggiunte così da raffinare la mappatura dei temi di cui ci occupiamo. Ve le segnalo già qui anche, poi nel file sono in giallo:
Violation, Education, Health (in sostituzione di health care)

Qui trovate il file: https://docs.google.com/spreadsheets/d/18vnzviUFbubLGNVg_84f8MIAE3obZdgtddizpLyHXbA/edit#gid=0

**Comment by cristigalas** [comment]
@luciroma visto il file e proposte. Allora _healthcare_ non si può togliere o sostituire perché label agganciata alla web form e alla categoria su Tutte le segnalazioni. Quindi la mia proposta è che aggiungiamo due nuove etichette (extra form e categorie sito), ovvero _Violation_ e _Education_ che aggiungiamo noi nelle issue corrispondenti, oltre a quelle già esistenti. 
Se volete le attivo subito e le chiamo _AA Violation_ e _AA Education_ così sono facili da identificare. 
E vediamo come va.

**Comment by iltempe** [comment]
qui? chiudo?

**Comment by cristigalas** [comment]
@iltempe Si creare label ad hohoc per AA.
