### ISSUE TITLE
New logo/favicon/cards?

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/ukrainehelp.emergenzehack.info#60]
@favoeva 
![image](https://user-images.githubusercontent.com/14352721/158813766-183a67d1-ab28-4283-b123-9cc36e91b466.png)

**Comment by favoeva** [comment]
le cards sono queste 
![card bambini](https://user-images.githubusercontent.com/9965333/161442792-4178a874-351c-46d9-a208-da4a91dab603.jpg)

**Comment by favoeva** [comment]
![card formazione e lingua italiana](https://user-images.githubusercontent.com/9965333/161442813-ad6ecb25-0cac-4aee-9ae4-18f16587d55b.jpg)

**Comment by favoeva** [comment]
![photo5926831397492865268](https://user-images.githubusercontent.com/9965333/161442857-a124ed71-2244-415d-9908-88d1a4b40107.jpg)

**Comment by favoeva** [comment]
![Uploading call to action.jpg…]()

**Comment by favoeva** [comment]
![logo account social](https://user-images.githubusercontent.com/9965333/161443181-56e64105-8a0b-40ad-ba6a-7591b939640f.jpg)

**Comment by favoeva** [comment]
Mauro Biani per UkraineHelpIT 

![mauro biani per UkraineHelpIT](https://user-images.githubusercontent.com/9965333/161443269-8c89ba26-8a9f-4103-ab1e-1c7da2609317.jpg)
