### ISSUE TITLE
Gestione pubblicazioni su mastodon

### ISSUE THREAD

**Issue by favoeva** [emergenzeHack/ukrainehelp.emergenzehack.info#61]
https://mastodon.uno/@UkrainehelpIT

**Comment by favoeva** [comment]
È possibile avere una label su github per pubblicazione issue su mastodon ?

**Comment by mfortini** [comment]
Intanto ho fatto un post con il post fissato di twitter, così almeno la timeline è piena. Occorre anche seguire un po' di gente su mastodon in modo da creare un po' di rete

**Comment by cristigalas** [comment]
@mfortini appena ho un po' di tempo mi ci metto.

**Comment by mfortini** [comment]
Attivato anche il crosspost

**Comment by iltempe** [comment]
no ok. voi non state bene

**Comment by iltempe** [comment]
però questa cosa di avere un TWITTER solo per segnalazioni ukrainehelp non è mica una cattiva idea eh. pensiamoci.

**Comment by iltempe** [comment]
lascio qui i riferimenti https://www.youtube.com/watch?v=d1mzUYzoolg potrebbe non essere male integrarne una versione nostra sul nostro portale per dare a tutto un carattere anche "social"...che dite?

**Comment by mfortini** [comment]
Possiamo ad esempio avere masto.emergenzehack.info con gli account che vogliamo e poi fare embed nel sito

**Comment by cristigalas** [comment]
@mfortini @iltempe ma vale la pena aprire e gestire una nostra istanza? Considerando le energie che abbiamo, il numero comunque contenuto di utenti che possiamo raggiungere e, soprattutto, il fatto che non accettano invii massivi. Dovrebbe essere una pubblicazione tutta manuale.

**Comment by mfortini** [comment]
@cristigalas considera che se hai un'istanza tua puoi postare tutto ciò che vuoi, il limite sono le tue risorse hw. Il bello di mastodon è che gli altri ti possono seguire dalla loro istanza in modo autonomo. Comunque parliamone

**Comment by cristigalas** [comment]
@mfortini ah ok, se non c'è limite già meglio... comunque sì parliamone.

**Comment by iltempe** [comment]
l'idea di avere un mastodon emergenzehack che tuitta tutte le segnalazioni con #nomedelprogetto mi piace. consente di avere un canale che "trasmette" tutti i post dei nostri progetti all'occorrenza.

**Comment by cristigalas** [comment]
Attivata anche istanza https://masto.emergenzehack.info/@UkraineHelpIT
