### ISSUE TITLE
Bug lingue ITA-ENG Sito di progetto

### ISSUE THREAD

**Issue by LioKlingo** [emergenzeHack/ukrainehelp.emergenzehack.info#62]
**Priorità**: alta

## Richiesta
Il sito in italiano diventa in inglese nelle sezioni interne

## Come si riproduce il bug
 Un utente che clicca su un qualsiasi bottone della home, atterra su una pagina in lingua inglese. Se intravede la possibilità in alto a destra di agire sul tab "Language", cliccando si ritrova come per magia di nuovo nella Home in italiano. Quindi si crea un loop.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by cristigalas** [comment]
Aggiungo altri bug che vanno corretti rispetto al passaggio italiano/inglese:

1. Dalla homepage in italiano il bottone Segnala apre web form in inglese, mentre dal menù italiano in alto la web form si apre in italiano. Quindi credo basti correggere il link in home.
2. Se dalla web form in italiano si clicca su una delle categorie (ad. Chiedi Aiuto) si apre la form sempre in inglese, non in italiano. Andrebbero ovviamente messi titoli e campi in italiano.
3. Sempre nella versione italiano del sito, i titoli di tutte le pagine relative alle varie categoria di segnalazioni (Raccolte fondi, raccolte beni, ecc.) sono sempre in inglese, mentre dovrebbero essere in italiano e dalla homepage I bottoni dovrebbero portare alle pagine in italiano. Solo la pagina Tutte le segnalazioni ha il titolo in italiano ma se si arriva dal menù in alto (Scopri), dalla homepage invece punta alla pagina con titolo in inglese.
4. Ultimo ma non ultimo: è importante che nella pagina "Tutte le segnalazioni" anche i titoli dei vari bottoncini colorati che rimandano alle categorie tematiche siano in italiano.
5. E poi di default metterei la pagina in italiano o in alternativa metterei il cambio lingua bene in evidenza sul sito non nascosto nel menù in alto.

Per il momento mi pare tutto. Credo che questi interventi sia importanti oltre che urgenti per non disincentivare l'uso della piattaforma. Grazie a chi ci lavorerà!

**Comment by iltempe** [comment]
allora sicuramente qui si può migliorare molto ma discuterei punto per punto.

- i form sono tutti in inglese per ora. vanno tradotti tutti...c'è issue #27 
- se di default vogliamo si mette italiano no problem.
- la pagina tutte le segnalazioni la sistemo subito
- @LioKlingo per il loop che dici tu come faresti? se in home page vuoi cambiare lingua non vedo altre possibilità.

**Comment by cristigalas** [comment]
@iltempe intanto possiamo mettere in italiano i titoli delle varie pagine tematiche e mettere anche in homepage il bottone per il cambio lingua così è più visibile.

Poi la pagine Tutte le segnalazioni sì, va messa sia in italiano che in inglese, cioè vanno messi in entrambe le lingue sia titoli che bottoni.

Per le form: in issue #27 parliamo di form multilingue, mentre adesso basterebbe tradurre le form in italiano. Non si può riprendere il lavoro fatto per Covid19 e adattarlo? Anche se ovviamente un po’ di lavoro da fare c’è ma forse aiuterebbe.

Insomma se non miglioriamo la fruibilità della piattaforma per ciò che riguarda la traduzione in italiano rischiamo di perdere molto in termini di utenza.

**Comment by iltempe** [comment]
taggo @abonte e @martinapugliese

**Comment by iltempe** [comment]
form tradotti in italiano. grazie a @abonte

**Comment by cristigalas** [comment]
Grazieee @abonte!

**Comment by cristigalas** [comment]
I punti 3 e 4 che rimangono da fare li ho spacchettati in due nuove issue, vedi #83 e #82.
Quindi questa si può chiudere @iltempe.
