### ISSUE TITLE
Inserire comunicato stampa sul sito 

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/ukrainehelp.emergenzehack.info#63]
@iltempe qui il comunicato definitivo https://docs.google.com/document/d/1XodHRBv12ADqYYzPGM42jRF9D-CONBjLoax7yXOyjGc/edit?usp=sharing

Puoi per favore inserirlo sul sito. Dove dicevo ieri: in About con un link, in fondo al primo paragrafo, prima di Riuso, con frasina tipo: Leggi qui il comunicato stampa.

Grazie!

**Comment by iltempe** [comment]
fatto chiudo

**Comment by cristigalas** [comment]
@iltempe toglierei definitivo dalla frase.
