### ISSUE TITLE
Opendata non sono aggiornati

### ISSUE THREAD

**Issue by abonte** [emergenzeHack/ukrainehelp.emergenzehack.info#68]
**Priorità**: media

## Richiesta

I dati nella pagina `/opendata` contengono le segnalazioni del progetto covid19 e non di ukrainehelp.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by cristigalas** [comment]
O cavolo! Grazie @abonte! 
@iltempe spero che oggi prima di fare il tweet tu abbia corretto 😱

**Comment by iltempe** [comment]
@abonte dovrebbe essere ok. grazie mille
