### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/ukrainehelp.emergenzehack.info#7]
List of categories to collect in terms of content (labels...)

**Comment by MTO20** [comment]
Transportation
Accommodation
Food, hygiene and basic need items
Heath
Education
Translation
Psychological support
Legal support

**Comment by iltempe** [comment]
to add a "label" to identify a specific project, region ...something like "ukraine_place1" "ukraine_place2" "ukraine_place3" ...to decide once a new organization become part of the project.

**Comment by favoeva** [comment]
I would add 
Drugs - medications

**Comment by mfortini** [comment]
Please remember that the categories are now configured using the files here:
https://github.com/emergenzeHack/europehelp.info/tree/main/_data

**Comment by cristigalas** [comment]
And remember that categories and labels must be the same (more or less) and must be as broad and generic as possible (TCI and Covid19Italia teach!).

**Comment by cristigalas** [comment]
@iltempe questa si può chiudere mi pare, no?
