### ISSUE TITLE
Tradurre in italiano titoli pagine segnalazioni per categoria

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/ukrainehelp.emergenzehack.info#82]
Nella versione italiano del sito è importante tradurre in italiano i titoli di tutte le pagine relative alle varie categoria di segnalazioni (Raccolte fondi, raccolte beni, richieste di aiuto, ecc.). Adesso sono sempre in inglese, mentre dovrebbero essere in italiano.

Poi una volta tradotti i titoli delle pagine in italiano andrebbero agganciate a rispettivi bottoni presenti nella homepage italiana che ora portano a quelle in inglese.

**Comment by abonte** [comment]
risolto qui #88
