### ISSUE TITLE
Tradurre in italiano bottoni pagina “Tutte le segnalazioni”

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/ukrainehelp.emergenzehack.info#83]
Nella pagina in italiano "[Tutte le segnalazioni](https://ukrainehelp.emergenzehack.info/issues/)" sarebbe importante, anzi fondamentale ;) tradurre in italiano anche i titoli dei vari bottoncini colorati che rimandano alle categorie tematiche.

**Comment by iltempe** [comment]
fatto da @abonte
