### ISSUE TITLE
Proposta di una nuova categoria Istruzione nel form di segnalazione

### ISSUE THREAD

**Issue by abonte** [emergenzeHack/ukrainehelp.emergenzehack.info#84]
**Priorità**: bassa

## Richiesta

Aggiungere una nuova categoria relativa alle iniziative che offrono istruzione ed educazione nel form _Initiatives and Services_.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by cristigalas** [comment]
@abonte mi sembra un'ottima idea. Potremmo chiamarla Istruzione/Formazione o meglio Istruzione/Educazione? @luciaroma @favoeva che ne dite?

**Comment by Patriziacar** [comment]
Per me ottima idea, tra le due direi Istruzione/formazione

**Comment by favoeva** [comment]
Sono d’accordo 👍istruzione/formazione

**Comment by cristigalas** [comment]
Allora @abonte ok per Istruzione/Formazione!
@mfortini pensi tu poi ad attivare sul sito bottone con pagina dedicata e poi label? O mi dici quando è tutto ok e penso io a label…

**Comment by abonte** [comment]
Ho messo in inglese 'education and training' e in italiano 'istruzione e formazione'

**Comment by cristigalas** [comment]
Ok @abonte! Appena approvano pull e @mfortini fa categoria con pagina dedicata io procedo con Pavel su Github.

**Comment by cristigalas** [comment]
@iltempe questa issue si può chiudere.
