### ISSUE TITLE
Proposta nuova pagina con statistiche

### ISSUE THREAD

**Issue by abonte** [emergenzeHack/ukrainehelp.emergenzehack.info#85]
**Priorità**: bassa

## Richiesta

Proposta: creare un nuova pagina con le statistiche sulle segnalazioni. Per esempio, numbero di segnalazioni per tag.

## Risolto?

* [x] Ho verificato che il problema è stato risolto

**Comment by avivace** [comment]
I dati protrebbero essere serviti dalla nuova API https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info/issues/20

**Comment by cristigalas** [comment]
@abonte @avivace sarebbe ottimo! Su Covid19Italia.help le avevamo ed erano utili.

**Comment by luciroma** [comment]
concordo

**Comment by iltempe** [comment]
@abonte assegno a te quessto. non appena hai fatto fai pure pull, grazie ;-)

**Comment by iltempe** [comment]
@abonte mi pare di aver letto in chat che eri pronto con questa...sbaglio?

**Comment by abonte** [comment]
> @abonte mi pare di aver letto in chat che eri pronto con questa...sbaglio?

ecco una prima versione qui #119

**Comment by iltempe** [comment]
grande @abonte !!! ho fatto merge.
