### ISSUE TITLE
Etichetta legal support sul sito

### ISSUE THREAD

**Issue by Patriziacar** [emergenzeHack/ukrainehelp.emergenzehack.info#86]
**Priorità**: bassa

## Richiesta
Su github abbiamo 20 issues accettate ma selezionando dal sito l'etichetta Legal support non appare nulla https://ukrainehelp.emergenzehack.info/legal/

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by mfortini** [comment]
Fixed, il problema è che le label sono case sensitive e la label era Legal, mentre quella indicata nella configurazione era legal.
