### ISSUE TITLE
Scelta multipla Categorie Form "Servizi"

### ISSUE THREAD

**Issue by luciroma** [emergenzeHack/ukrainehelp.emergenzehack.info#93]
**Priorità**: media

## Richiesta

Ciao, inserendo alcune segnalazioni di iniziative e servizi via form, mi sono resa conto della necessità di poter opzionare più di una categoria tra quelle proposte e non una soltanto. Questo agevolerebbe non solo chi compila il form in entrata ma anche poi le editor in fase di ricezione e processamento della segnalazione stessa.

Help @mfortini @iltempe @avivace 

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by mfortini** [comment]
Ho cambiato la form e il backend per avere la funzionalità richiesta. Vi chiedo una verifica

**Comment by iltempe** [comment]
dovremmo aver fatto anche un po' di correzioni. da testare.
